spring.application.name=demo

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:espi_wealth}
spring.datasource.username=${DB_USER:espi}
spring.datasource.password=${DB_PASSWORD:espi_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
